### PR TITLE
show confirmation box on field choices modification

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fix https://github.com/Strategy11/formidable-pro/issues/4322

image

### CODE REVIEW

**Comment by AbdiTolesa** [comment]
> If I use the bulk editor or change the order of the options and leave the page the popup doesn't show.

Good points, those were not mentioned in the issue title but we definitely should cover them. Updated it now. Thanks!

**Review by garretlaxton — APPROVED** [review]
Nice, this looks great!

**Review by truongwp — APPROVED** [review]
This looks great! Thank @AbdiTolesa!

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa @truongwp and @garretlaxton!

This looks good to me 🚀.

**Pull request merged**
