### PR TITLE
only remove frm_logic_class when wp_is_json_request

### PR DESCRIPTION
**Pull request by Crabcyborg**
Fixes https://github.com/Strategy11/formidable-pro/issues/3001

### CODE REVIEW

**Review by jairoprez — COMMENTED** [review]
Hey Super @Crabcyborg I did some testing even without the recording tool turned on so as not to affect internet speed and it seems that hidden fields are still showing in a flash before hiding when loading the page https://recordit.co/2l70L76GY1

**Comment by Crabcyborg** [comment]
> Hey Super @Crabcyborg I did some testing even without the recording tool turned on so as not to affect internet speed and it seems that hidden fields are still showing in a flash before hiding when loading the page https://recordit.co/2l70L76GY1

@jairoprez hm, are you seeing the fading on any forms?

This is the default behaviour. You might not have the fade option turned on (in global settings):
Screen Shot 2021-05-03 at 9 42 30 AM

**Comment by jairoprez** [comment]
> @jairoprez hm, are you seeing the fading on any forms?
> 
> This is the default behaviour. You might not have the fade option turned on (in global settings):

Ah sorry @Crabcyborg , you were right, I had the fade in option turned off :sweat_smile:, after turning it on everything worked as expected, thanks for pointing that out. https://recordit.co/rHgFoWDShR

**Review by jairoprez — APPROVED** [review]

**Review by stephywells — APPROVED** [review]
Nice solve. Looks like a great way to solve it.

**Pull request merged**
