### PR TITLE
Fix PHP notice with array_diff_assoc() when exporting form

### PR DESCRIPTION
**Pull request by truongwp**
This fixes issue https://github.com/Strategy11/formidable-pro/issues/2999

### CODE REVIEW

**Comment by truongwp** [comment]
@Crabcyborg Thanks for checking. Maybe we need one more loop with this `$array_saved = array_filter( $saved, 'is_array' );`.

Or we can loop through `$defaults` to remove the same entries from `$saved`, without using `array_diff_assoc()`. 

How do you think?

**Comment by Crabcyborg** [comment]
> How do you think?

@truongwp yeah, that sounds like it should do the trick!

**Comment by truongwp** [comment]
@Crabcyborg I have updated it. Please check when you have time.

**Review by Crabcyborg — APPROVED** [review]
Thank you @truongwp this looks good to me!

**Review by jairoprez — APPROVED** [review]
I did some testing and PHP notice has been fixed http://recordit.co/RG7W2GbdXD 💪

**Pull request merged**
