### PR TITLE
make dropdown height match date inputs

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Make Date options dropdown height match date inputs.
**Before**:
image

**After**:
image

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@AbdiTolesa I don't think this is the proper fix for this issue at all.

It looks like the height is already good on Firefox. I only see the inconsistent height in Chrome.

If you do try this fix in Firefox, it looks worse than it does in Chrome without this fix,
Screen Shot 2023-04-05 at 9 59 40 AM

We also don't want any references to `#form_reports_page` in the lite plugin.

I played with it for a moment and I found I had the best results by using a smaller font for date fields.
```
.frm_wrap input[type="date"] {
	font-size: var(--text-sm);
}
```

The font size difference bumps it down 2px which I don't find too noticeable.
Screen Shot 2023-04-05 at 10 01 17 AM

What do you think?

**Comment by Crabcyborg** [comment]
@stephywells What do you think about bumping down the font size on the date input?

Or do you think there's a better solution we should go with?

**Comment by stephywells** [comment]
This PR isn't needed. I already fixed this here:
https://github.com/Strategy11/formidable-forms/pull/1134

**Comment by Crabcyborg** [comment]
> This PR isn't needed. I already fixed this here: #1134

@stephywells  The select is 30px high and the date fields are 33.71px.

Screen Shot 2023-04-05 at 12 18 15 PM
Screen Shot 2023-04-05 at 12 18 56 PM
Screen Shot 2023-04-05 at 12 19 02 PM

If that doesn't matter, I'll just close this.

**Comment by stephywells** [comment]
I see it now. Looks like this needs to be overridden. New PR incoming.

```
::-webkit-datetime-edit {
    line-height: 1.85714286;
}
```

**Pull request closed without merging**
