### PR TITLE
Address UI Enhancements and Inconsistencies

### PR DESCRIPTION
**Pull request by shervElmi**
This PR focuses on implementing UI improvements and rectifying inconsistencies identified by Razvan, including button hover states, cursor pointers, shadow consistencies, and enhancing chevron behavior in the form builder.

## Required Formidable Pro Branch:
https://github.com/Strategy11/formidable-pro/tree/issue-4301

## Related Issue:
[UI enhancements and inconsistencies #4301](https://github.com/Strategy11/formidable-pro/issues/4301)

## QA URL
https://qa.formidableforms.com/sherv12/wp-admin/?page=formidable-views-editor&view=19

## Testing Instructions:
1. Check that disabled buttons no longer show hover styling.
2. Verify 'cursor:pointer' appears on the "Insert view into application" chevron and similar elements.
3. Confirm shadow consistency on the Application page and ensure it matches the style templates.
4. Evaluate the improved chevron behavior when collapsing/expanding a page in the form builder.

## Output Video
https://www.loom.com/share/218ab4ad41eb44feba2159206351674e?sid=c9738cbe-cbbd-4354-a1fd-4bbe9bb046c1

### Prototypes
- [Chevron Behavior Prototype](https://www.figma.com/proto/ix4WldrDqaRYhfB3dbZ5Jd/Scratchpad?page-id=250%3A703&type=design&node-id=251-706&viewport=1033%2C257%2C0.39&scaling=scale-down&starting-point-node-id=251%3A706)
- [Page Break Field Behavior](https://cln.sh/4bgSpQkG)

### CODE REVIEW

**Review by garretlaxton — APPROVED** [review]
This looks great!

**Review by truongwp — APPROVED** [review]
This looks good. Thanks @shervElmi!

**Comment by Crabcyborg** [comment]
> Required Formidable Pro Branch:
> https://github.com/Strategy11/formidable-pro/tree/issue-4301

@shervElmi Is there no PR for this update?

**Comment by shervElmi** [comment]
Yes, @Crabcyborg, it is just a single line of CSS code and is part of this PR.

Comparing changes URL: https://github.com/Strategy11/formidable-pro/compare/master...issue-4301

**Comment by Crabcyborg** [comment]
@shervElmi That's just a branch though? Can you make a PR?

**Comment by shervElmi** [comment]
> @shervElmi That's just a branch though? Can you make a PR?

Sure!

**Comment by shervElmi** [comment]
@Crabcyborg, here is the PR for the pro branch: https://github.com/Strategy11/formidable-pro/pull/4564

**Review by Crabcyborg — APPROVED** [review]
Thanks @shervElmi @truongwp and @garretlaxton!

I think this is good to go.

🚀

**Pull request merged**
