### PR TITLE
Side by side fields

### PR DESCRIPTION
**Pull request by Crabcyborg**
@garretlaxton I have a couple items still on my list [here](https://github.com/Strategy11/formidable-pro/issues/3074) but other than that I think this is pretty close.

I could use your help trying to find anything else. I plan to release this tomorrow.

There's also some lower priority items on my list [here](https://github.com/Strategy11/formidable-pro/issues/3118).

### CODE REVIEW

**Comment by garretlaxton** [comment]
So far, text fields work great for me. 

My only issues were with the other fields not immediately resize according to the CSS until I update the form. 

I also can't get the buttons to work in the More Options. It also seems the More Options popup overlaps the delete confirmation.
Screenshot 2021-08-10 at 16-08-43 Formidable Forms ‹ Formi QA — WordPress

Will keep looking, but this is what I see so far.

**Comment by Crabcyborg** [comment]
> I also can't get the buttons to work in the More Options. It also seems the More Options popup overlaps the delete confirmation.
> Screenshot 2021-08-10 at 16-08-43 Formidable Forms ‹ Formi QA — WordPress

Hm, that's odd. I can't seem to replicate any issues with this.

It might be cache? A hard refresh may help.

Do you see JavaScript errors maybe?

I've pushed a few more updates. My initial list is basically empty now. I noticed that I can't seem to drag an existing section beside another one, but other than that things seem to check out for me.

**Comment by garretlaxton** [comment]
@Crabcyborg Clearing cache solved this issue for me.

**Comment by garretlaxton** [comment]
Something else I notice is when I have a field below or above a section, it looks like it's included in that section. The field label is also out of place appearing next to the input box.

Screenshot 2021-08-10 at 19-48-22 Formidable Forms ‹ Formi QA — WordPress

Screenshot 2021-08-10 at 19-48-38 Sample Page – Formi QA

**Pull request merged**
