### PR TITLE
Issue 3798

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fixes https://github.com/Strategy11/formidable-pro/issues/3798

This update fixes a minor styling issue for rtl languages in the form builder.

Before:
image

Now:
image

### CODE REVIEW

**Comment by AbdiTolesa** [comment]
> @AbdiTolesa We already have some RTL rules in our main CSS
> 
> https://github.com/Strategy11/formidable-forms/blob/63f7c1c4d45ffc6ba5d017ddafc9c287bcd678e2/css/frm_admin.css#L7836
> 
> Does it work to just add the rules there with the `.rtl` prefix?

@Crabcyborg Yes I just checked that and that also seems to work indeed. Thank you!

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa I haven't tested it yet but it looks good!

@garretlaxton Could you give this a look when you get a chance? Thank you!

**Comment by garretlaxton** [comment]
This looks good.
localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291

I do notice some other places that could use some improvement though.
- When you click the more options of a field the close button should have a bit more spacing
localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291 (1)

- Conditional logic
localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291 (2)

**Comment by AbdiTolesa** [comment]
> This looks good. localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291
> 
> I do notice some other places that could use some improvement though.
> 
> * When you click the more options of a field the close button should have a bit more spacing
>   localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291 (1)
> * Conditional logic
>   localhost_qa-form_wp-admin_admin php_page=formidable frm_action=edit id=291 (2)

@garretlaxton I just pushed a few updates for covering those as well. Thank you!

**Comment by AbdiTolesa** [comment]
> Those changes look good on RTL. However, these issues appears on LTR now. ltr1 ltr2

@garretlaxton sorry about breaking another style on the last update. That is just fixed now.

**Review by garretlaxton — APPROVED** [review]
Sweet! This looks great on both sides now!

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa and @garretlaxton 🚀

**Pull request merged**
