### PR TITLE
Design Enhancements for Field Group Pop-up

### PR DESCRIPTION
**Pull request by shervElmi**
This PR introduces design improvements to the field group pop-up, following the Interface Reviews conducted by Razvan.

Figma URLs:
[Link to Figma Design Part One](https://www.figma.com/file/7Kwlv3H2ShYEI0wekWnPBb/Interface-Review-Fixes?type=design&node-id=845-109&t=s47Uuwq8mWWTURWV-4)
[Link to Figma Design Part Two](https://www.figma.com/file/7Kwlv3H2ShYEI0wekWnPBb/Interface-Review-Fixes?type=design&node-id=845-114&t=s47Uuwq8mWWTURWV-4)

## QA URL:
https://qa.formidableforms.com/sherv3/wp-admin/admin.php?page=formidable&frm_action=edit&id=10

## Testing Instructions:
1. Navigate to `WP Admin > Formidable`.
2. Open an existing form or create a new one.
3. Add some fields in the same row.
4. Verify that the field group pop-up option displays as shown in the "After" screenshots below.

### Before
image
image

### After
image
image

### CODE REVIEW

**Comment by garretlaxton** [comment]
This looks good! One thing I do notice though is in figma it's changed to `Break into different rows` instead of `Break into rows`.

**Comment by shervElmi** [comment]
> This looks good! One thing I do notice though is in figma it's changed to `Break into different rows` instead of `Break into rows`.

Indeed, I've noticed that as well. Additionally, I see that `Layouts are based on a 12-columns grid system` has been changed to `Our layout is built based on a 12-columns grid system`. @Crabcyborg, I'd appreciate your input on these text changes.

**Review by omidakhavans — APPROVED** [review]
This looks great Thank you.

**Review by Crabcyborg — APPROVED** [review]
Thanks @shervElmi @omidakhavans and @garretlaxton for working on this!

🚀

**Comment by shervElmi** [comment]
> Thanks @shervElmi @omidakhavans and @garretlaxton for working on this!
> 
> 🚀

Thanks, @Crabcyborg! Could you please close the following issue?
https://github.com/Strategy11/formidable-pro/issues/3379

**Pull request merged**
