### PR TITLE
Keeps WordPress sidebar full width on larger screens

### PR DESCRIPTION
**Pull request by LauraSteiner**
Keeps WordPress sidebar full width on larger screens

https://github.com/Strategy11/formidable-pro/issues/2389

### CODE REVIEW

**Comment by stephywells** [comment]
@LauraSteiner I made a few changes to prevent the javascript from affecting Chrome. I was seeing some jumping in Chrome. I tested this in Chrome and Edge. Is it possible to test my changes in other browsers too?

**Comment by LauraSteiner** [comment]
@stephywells Thanks!  That check for Chrome is very cool!  

I think it could be good to set the default to scrollbar-cushion to something like 7px so there's room for both scrollbars when the window is short.  If it's set to 0px, when the window is short, there's an outer scrollbar to scroll the main page, but the inner scrollbar to scroll the right form builder panel doesn't show.

In this video, you can hopefully see the scrollbar for the right form builder when the window is long enough to accommodate the full WP sidebar.

When it's too short, you can hopefully see that there's a right scrollbar for the main windows, but there's no scrollbar for the right panel of the form builder.

https://cl.ly/9442f7839852

**Comment by LauraSteiner** [comment]
In Edge on Windows, the scrollbars overlap just a bit.  It looks like if the scrollbar cushion were 2px or 3px bigger, this wouldn't happen.

https://cl.ly/17624900c26a

**Comment by LauraSteiner** [comment]
Vivaldi is Chromium based, but only the outer scrollbar shows and works when the cushion is set to 0 and the screen is full length.  With Chrome in the same situation, the form builder right panel shows.

**Comment by LauraSteiner** [comment]
@stephywells I'm interested in hearing your thoughts on this.  

What do you think of making the default scrollbar cushion on Chrome to something like 7 - 8 px instead of 0?  Then there would be a scrollbar on the right form builder panel when the screen is shorter.

**Comment by stephywells** [comment]
@LauraSteiner I'm fine with a bigger padding in the javascript. Whatever you think looks good there. You can make the adjustments you think should be made. But Chrome shouldn't be changing with javascript. Chrome is the priority and we should only use CSS there.

@srwells any thoughts on this?

**Pull request closed without merging**
