### PR TITLE
Add Stripe PRs 315, 316, and 318

### PR DESCRIPTION
**Pull request by Crabcyborg**
This includes 3 Stripe Add-on Updates,

- https://github.com/Strategy11/formidable-stripe/pull/315
- https://github.com/Strategy11/formidable-stripe/pull/316
- https://github.com/Strategy11/formidable-stripe/pull/318

### CODE REVIEW

**Comment by garretlaxton** [comment]
For 316, I'm not getting any decline error when using the `4000000000000341` card.

**Comment by Crabcyborg** [comment]
> For 316, I'm not getting any decline error when using the `4000000000000341` card. I do have Pro disabled, if that makes any difference.

Thanks @garretlaxton. I think that's also an issue with the update in the Stripe add on.

I made a new PR there first https://github.com/Strategy11/formidable-stripe/pull/320.

Can you confirm this fixes those issues? Then I'll copy them over into Stripe Lite.

**Comment by Crabcyborg** [comment]
@garretlaxton This is updated now. It should work better now when testing the issue fixed by PR 316.

**Comment by garretlaxton** [comment]
This looks good, but for 318, is it normal that I still need to connect to staging.formidableforms.com?

**Comment by Crabcyborg** [comment]
Thanks @garretlaxton.

For PR 318, there is no related API requirement, so that shouldn't be the case.

it works as expected for me. 
vWkulHBBtE

It's a JS update, so maybe you were loading the minified script, or a cached script?

**Comment by garretlaxton** [comment]
Do you have FF Pro enabled? I am directed back to a blank page after I fail the transaction.

Here is my URL.
https://formi.grunge.us.eu.org/wp-admin/admin-ajax.php?action=frm_forms_preview&form=aastripe

**Review by garretlaxton — APPROVED** [review]
Ahh, okay. I disabled Pro, but not Stripe Pro. This looks good.

**Comment by Crabcyborg** [comment]
Thanks Garret!

🚀

**Pull request merged**
