### PR TITLE
Turnstile

### PR DESCRIPTION
**Pull request by Crabcyborg**
**ClickUp Task** https://app.clickup.com/t/863gnr0kv
**ClickUp Overview** https://app.clickup.com/9006050445/v/dc/8ccuv4d-20611/8ccuv4d-16931

Requires this PR in Pro or the validation will fail when Pro is active https://github.com/Strategy11/formidable-pro/pull/4852

**This update**
- Adds a new Turnstile option to the global settings Captcha section.
- When Turnstile is active, Captcha fields will include a "Captcha Theme" setting which has options for "Light", "Dark" and "Auto". "Auto" uses your operating system's Dark mode settings.
- When hCaptcha is active, Captcha fields will include a "Captcha Theme" setting which has options for "Light", "Dark".
- When Turinstile or hCaptcha is active, Captcha fields will include a "Captcha Size" setting which has options for "Normal" and "Compact".

**When testing, it would be good to test reCAPTCHA and hCaptcha as well. The captcha code has been pretty heavily refactored.**

**Screenshots**
Screen Shot 2024-03-04 at 1 04 58 PM

Screen Shot 2024-03-04 at 1 05 26 PM

Screen Shot 2024-03-04 at 1 05 29 PM

Screen Shot 2024-03-04 at 1 07 20 PM

**This update also adds "Captcha Size" settings for both hCaptcha and Turnstile fields.**
**Here are some Compact captcha examples**
Screen Shot 2024-03-04 at 2 35 15 PM
Screen Shot 2024-03-04 at 2 35 01 PM

This update also adds support for "Dark" mode with hCaptcha.
Screen Shot 2024-03-04 at 2 39 39 PM

### CODE REVIEW

**Comment by garretlaxton** [comment]
This works great with all the captchas. I do notice that the Turnstile gif in the builder is pretty big compared to the others.
image
image

**Review by stephywells — APPROVED** [review]
Awesome! This is a great code cleanup too. It's so much more readable and clear. It's perfect!

**Comment by Crabcyborg** [comment]
Thanks Garret.

I think you could be loading a stale version of the admin CSS.

I did set a 300px max-width on the element in the builder.

It should be a bit closer, though it is still larger.

Screen Shot 2024-03-06 at 3 48 20 PM

Screen Shot 2024-03-06 at 3 46 47 PM

Screen Shot 2024-03-06 at 3 47 03 PM

**Review by garretlaxton — APPROVED** [review]
Yes, you are right. This looks great!

**Pull request merged**
