### PR TITLE
TinyMCE Email Actions + Shortcode popup fix

### PR DESCRIPTION
**Pull request by Crabcyborg**
Includes https://github.com/Strategy11/formidable-forms/pull/885
And includes an update from Abdi that supports this update https://github.com/Strategy11/formidable-forms/pull/873

Fixes https://github.com/Strategy11/formidable-pro/issues/3737
Fixes https://github.com/Strategy11/formidable-pro/issues/3757

This update adds support for a rich text editor in email actions, which is a fairly highly voted feature request https://team.strategy11.com/feature-requests/2021/04/30/wysiwyg-email-editor/?modal=1

The shortcode popup will now appear directly below the text areas so it doesn't get in the way of seeing the content.
https://github.com/Strategy11/formidable-pro/issues/3757

### CODE REVIEW

**Review by garretlaxton — APPROVED** [review]
This looks great! Emails come through as formatted in the rich text field.
formi grunge us eu org_wp-admin_admin php_page=formidable frm_action=settings id=160 t=email_settings

Shortcode options also work great.
formi grunge us eu org_wp-admin_admin php_page=formidable frm_action=settings id=160 t=email_settings (1)

**Comment by stephywells** [comment]
@Crabcyborg is there something we could do to easily show the HTML only if the box is checked to send as plain text?

**Comment by stephywells** [comment]
I'm seeing a few issues:
1. The field box doesn't show when I type into a rich text field. The X could use a bit better centering.
Screen Shot 2022-09-14 at 9 33 46 AM

2. After opening an email form action, typing in the box, then adding another email action, the Visual tab isn't working.
Screen Shot 2022-09-14 at 9 37 29 AM

3. I think this would work better if the box were a little shorter. The problem is that sometimes the field box opens off the screen.

**Comment by Crabcyborg** [comment]
Thanks @stephywells I think I'll hold off from releasing this update today.

@AbdiTolessa When you get back could you look into #1 from Steph's comment? I'll try to address the other items. Thanks! https://github.com/Strategy11/formidable-forms/pull/895#issuecomment-1246955246

**Comment by Crabcyborg** [comment]
>     2. After opening an email form action, typing in the box, then adding another email action, the Visual tab isn't working.

Thanks @stephywells it looks like I only had it initializing properly on pre-existing actions and needed it for new actions as well. I moved where the code is so it uses the `frm-action-loaded` event I'm using in Quiz Outcomes.

>     3. I think this would work better if the box were a little shorter. The problem is that sometimes the field box opens off the screen.

Sounds good! I decreased the `textarea_rows` to 6 and I set a 160 height to the TinyMCE init for the email actions. What do you think about this for size?

Screen Shot 2022-09-16 at 1 19 44 PM
Screen Shot 2022-09-16 at 1 19 41 PM

**Comment by stephywells** [comment]
@garretlaxton would you mind reviewing this once more?

**Comment by garretlaxton** [comment]
I originally thought the visual tab was cache related as I cleared my cache and it seemed to work for me, sorry I missed that one!

This looks good, but I do notice when adding a URL from the visual tab a red border stays around the URL until you save the page or switch to the text tab.
localhost_qa-form_wp-admin_admin php_page=formidable frm_action=settings id=302

**Comment by stephywells** [comment]
I'm still seeing a couple weird behaviors. Here's one where the field options close immediately:
https://user-images.githubusercontent.com/1116876/191303872-80623b33-aef5-4d2d-827f-ab13d8ce7299.mp4

I'm also seeing a blank box when I add a new email action and click the ... on the visual tab:
Screen Shot 2022-09-20 at 9 45 06 AM

**Comment by Crabcyborg** [comment]
> Also, should the ... show in the outcome quiz action yet?

I'll add it in with next release. Adding it now without this update it won't work very well.

> That box is also a bit tall still. I'm not sure what is handled here and what isn't.

Right now this is all email-specific and the outcomes are initializing with separate code that's all in the quiz add on.

I just released the outcome quizzes but I could work on making it smaller for next release.

**Comment by stephywells** [comment]
> @Crabcyborg The immediate open/close issue seems to be solved now. Regarding repositioning the ... and X, should it just be centered to the box or just push it a bit to the left? just to be precise about it.

It needs to go down a couple pixels to be centered vertically between those two borders. I think it's fine horizontally to avoid overlapping with the resizing thing in the corner.

**Comment by Crabcyborg** [comment]
Thanks @AbdiTolesa for updating this! It looks good on my end!

@stephywells @garretlaxton As this has been updated a few more times, I think it could use another look. I think this looks ready for this week's release though! 🥳

**Comment by garretlaxton** [comment]
This looks a lot better, but I notice after updating the action the field options are missing still.
image

It also looks like the border around the formatting options is a bit too big. (See the bold option)
formi grunge us eu org_wp-admin_admin php_page=formidable frm_action=settings id=166 t=email_settings

**Comment by Crabcyborg** [comment]
> This looks a lot better, but I notice after updating the action the field options are missing still. image

@garretlaxton The only way I can recreate this is if I have no fields in my form. Any other tips on how to cause this to happen?

> It also looks like the border around the formatting options is a bit too big.

Thanks @garretlaxton the icons seemed pretty off with some of our Formidalbe styles. I added a commit that avoids the problematic ones.

It should look like this now.
Screen Shot 2022-09-27 at 3 03 45 PM

**Comment by garretlaxton** [comment]
I do have fields in the form. I am seeing this when I update the form or add a new email action to the form.
image

The format buttons look great now though.

**Comment by Crabcyborg** [comment]
Thanks @garretlaxton I didn't really understand how to replicate it until now! It should be fixed now.

**Review by garretlaxton — APPROVED** [review]
Sweet this looks great now!

**Pull request merged**
