### PR TITLE
Fix text input advanced option button style

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fixes https://github.com/Strategy11/formidable-pro/issues/3860
It looks like text inputs with advanced option are injected into the DOM when form actions are loaded but textarea fields are already loaded in different places on page loads. It might make sense to leave the css style for textarea SVGs as is but fix these for text fields when form actions are loaded.

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@AbdiTolesa I think we also want to keep the old right positioning. It's a lot more offset inside of the field with the previous update too.

**Before last update**
Screen Shot 2022-10-21 at 9 46 54 AM

**After**
Screen Shot 2022-10-21 at 9 47 20 AM

**Comment by AbdiTolesa** [comment]
> @AbdiTolesa I think we also want to keep the old right positioning. It's a lot more offset inside of the field with the previous update too.
> 
> **Before last update** Screen Shot 2022-10-21 at 9 46 54 AM
> 
> **After** Screen Shot 2022-10-21 at 9 47 20 AM

@Crabcyborg This is fixed now, thanks!

**Comment by garretlaxton** [comment]
Here's what I'm seeing.
image

**Review by Crabcyborg — APPROVED** [review]
Thanks for making a look @garretlaxton.

The icons look a lot better with this update to me!

Thanks @AbdiTolesa!

**Pull request merged**
