### PR TITLE
6.0 styles (#1034)

### PR DESCRIPTION
**Pull request by stephywells**
* a few layout fixes for small screens
* set secondary button to white instead of transparent
* update a few icons 
* more consistent padding/margins
* icon vertical alignment
* Make verify on destructive actions red
* Move some buttons into header 
* More consistent search box
* Use small buttons in table filtering
* Use css grids for form template list
* Apply more css to modals and Views page with frm-white-body class
* Style all buttons on frm-white-body
* Psalm fixes
* use compatible return type

### CODE REVIEW

**Comment by Crabcyborg** [comment]
I think this only happens in Firefox but the Bulk actions dropdown has vertical alignment issues when I try this branch.

Screen Shot 2023-01-27 at 12 58 13 PM

**Comment by Crabcyborg** [comment]
I'm noticing the TinyMCE editor used for HTML field descriptions has really funny looking buttons with this update.

**Before**
Screen Shot 2023-01-27 at 1 00 02 PM

**After**
Visual Text

**Comment by Crabcyborg** [comment]
The add button for applications is huge.

Screen Shot 2023-01-27 at 1 23 22 PM

**Comment by garretlaxton** [comment]
The Before Input and Visibility options in the advanced form options are a bit unaligned.
image

**Comment by Crabcyborg** [comment]
Is the form template search meant to be so small now?

**Before**
Screen Shot 2023-01-27 at 1 26 38 PM

**After**
Screen Shot 2023-01-27 at 1 27 08 PM

**Comment by Crabcyborg** [comment]
When I try to create an application with existing items I notice that the checkboxes are now all on the a separate line from the item labels.

Screen Shot 2023-01-27 at 1 28 54 PM

**Comment by Crabcyborg** [comment]
I notice there's a red confirmation button for deleting some things. I didn't see that being used though for the "Delete all entries" button.

Screen Shot 2023-01-27 at 1 45 37 PM

**Comment by stephywells** [comment]
Thanks for catching these @Crabcyborg ! They are all fixed.

I forgot to mention there is also a Pro PR for this too. You can find it here:
https://github.com/Strategy11/formidable-pro/pull/4035

**Comment by garretlaxton** [comment]
After deleting an application the modal doesn't go away.
image

**Comment by garretlaxton** [comment]
The application settings modal seems to go off the page.
image

**Comment by Crabcyborg** [comment]
I was seeing the same thing with the Settings pop as Garret.

I also noticed my long application name had an overlap issue with the dropdown arrow.
New Restaurant Menu

**Comment by stephywells** [comment]
> After deleting an application the modal doesn't go away. 

@garretlaxton This doesn't look related to my changes. Would you mind opening a new issue for this one?

**Comment by stephywells** [comment]
Thanks for the testing! All these issues are fixed, but some are in the pro branch here:
https://github.com/Strategy11/formidable-forms/pull/1037

**Comment by stephywells** [comment]
This has been merged into https://github.com/Strategy11/formidable-forms/pull/1039. All new commits will go into that branch.

**Pull request closed without merging**
