### PR TITLE
Reduce space between fields using Inside position

### PR DESCRIPTION
**Pull request by truongwp**
This fixes https://github.com/Strategy11/formidable-pro/issues/3844

Thanks @stephywells for the CSS code.

### CODE REVIEW

**Review by stephywells — CHANGES_REQUESTED** [review]
Thanks @truongwp for being so fast!

I just found a design from Yaro on this. Let's do this one where the label doesn't go all the way above the field.
https://www.figma.com/file/Y8rOu6zzVHBFvE0YZwhxbU/Visual-reviews?node-id=15%3A591

Let's also change the label in the settings and styler from "Placeholder leave the space" to "Floating"

**Comment by truongwp** [comment]
@stephywells Which design will we implement? 1 or 2?

Screen Shot 2022-10-04 at 10 38 17

**Comment by stephywells** [comment]
@truongwp sorry that wasn't very clear. I was thinking the first one so we can keep the field heights the same as they are now.

**Comment by truongwp** [comment]
@stephywells Since we decided to work on that design later. Can this PR be merged?

**Comment by Crabcyborg** [comment]
@stephywells Should I merge this or should we hold off on this update?

**Comment by stephywells** [comment]
@Crabcyborg @truongwp I just made one more small update on this so the label would be aligned with the field. It looked weird for fields with a description or when fields had a top label too.

This looks good to go! Thanks @truongwp for your help and patience on this!

**Review by stephywells — APPROVED** [review]

**Pull request merged**
