### PR TITLE
add read only setting to name field

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fixes https://github.com/Strategy11/formidable-pro/issues/4306
Just adding a "read only" field setting to Name field.

image

### CODE REVIEW

**Review by garretlaxton — APPROVED** [review]
This looks great!

**Review by truongwp — APPROVED** [review]
This looks great! Thank @AbdiTolesa!

**Review by Crabcyborg — CHANGES_REQUESTED** [review]
@AbdiTolesa As far as I can tell, `read_only` is actually a Pro feature.

If you disable Pro, and go to all of the basic fields, there is no read only option. When you enable Pro, they appear.

See my recording. The setting never sticks.
U4M36KySvh

Can we move this update to Pro so it's consistent with the other fields?

**Comment by AbdiTolesa** [comment]
> @AbdiTolesa As far as I can tell, `read_only` is actually a Pro feature.
> 
> If you disable Pro, and go to all of the basic fields, there is no read only option. When you enable Pro, they appear.
> 
> See my recording. The setting never sticks. Because Pro is inactive. U4M36KySvh
> 
> Can we move this update to Pro so it's consistent with the other fields?

@Crabcyborg I never thought about that but I have created a similar update in pro now, (https://github.com/Strategy11/formidable-pro/pull/4334) thanks!

**Pull request closed without merging**
