### PR TITLE
Fix: parameters getting stripped from connect flow

### PR DESCRIPTION
**Pull request by stephywells**
Remove the old v1 connect js since it was unused

Firefox is removing all paramters from the URL if any utms are included. This removed the utms so the link will work.

### CODE REVIEW

**Review by shervElmi — APPROVED** [review]
Thank you for your work on this issue, @stephywells! I've tested it on my QA site, and it works.

**Review by Crabcyborg — APPROVED** [review]
I just uploaded a Formidable Lite beta to QA and tested it there, and it worked for me, for the first time ever 😅.

I'm used to only seeing error messages on this page.

Screen Shot 2024-02-14 at 4 54 22 PM

It's also exciting to see a ton of code getting removed 🥳.

🚀

**Comment by stephywells** [comment]
Yay!! That's great news!!

**Comment by Crabcyborg** [comment]
@stephywells Since this didn't make it into today's release, do you think it's worth making another Lite release tomorrow so this gets out too?

**Comment by stephywells** [comment]
Well... Looks like another issue came up, so this would be great to include in the release.

**Pull request merged**
