### PR TITLE
Include HubSpot signup

### PR DESCRIPTION
**Pull request by stephywells**
This PR does a few things:
- Before, MailChimp shows in the top row of the form actions. This replaces MailChimp with HubSpot.
- The message shown for add-ons in the upgrade modal can be customized with data-message (the same as fields)
- Allow links in the download excerpt on the add-ons list page
- If the message is customized, show it separately from the upgrade button
- Add a custom message in the HubSpot class

There are three different scenarios for this modal:
1. Only Lite installed
2. Pro installed without access to HubSpot
3. Pro installed with access to HubSpot

(When the HubSpot add-on is installed, nothing should be different since the modal doesn't show.)

### CODE REVIEW

**Comment by Crabcyborg** [comment]
Thanks @stephywells I haven't tested this but it looks good.

Looks like you're failing a couple phpcs tests at the moment though.

https://github.com/Strategy11/formidable-forms/pull/549/checks?check_run_id=3724364893
Screen Shot 2021-09-28 at 9 35 13 AM

**Comment by garretlaxton** [comment]
I'm not too sure where to test these changes. Any hints?
```
- The message shown for add-ons in the upgrade modal can be customized with data-message (the same as fields)
- Allow links in the download excerpt on the add-ons list page
- If the message is customized, show it separately from the upgrade button
- Add a custom message in the HubSpot class
```

**Comment by stephywells** [comment]
Sorry @garretlaxton.

To test this, you can click the HubSpot icon in the form actions settings for any form. It probably doesn't really needs extra QA, but it wouldn't hurt to take a look with just the Lite version installed, and with Pro active.

**Comment by garretlaxton** [comment]
Ahh okay, @stephywells. Yes, I did see and test the changes with HubSpot. But just wasn't sure about the add-on page customization.

**Review by garretlaxton — APPROVED** [review]

**Pull request merged**
