### PR TITLE
Try to render captcha a second time on a timeout

### PR DESCRIPTION
**Pull request by Crabcyborg**
Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1729107464507059

Now if the form immediately becomes visible (within the next second), the captcha will still render.

### CODE REVIEW

**Comment by engahmeds3ed** [comment]
[formidable-6.15.1-beta.zip](https://github.com/user-attachments/files/17415570/formidable-6.15.1-beta.zip)

Zip file from that change.

@Crabcyborg just to confirm, we are sure that one second is enough time, correct?

**Comment by Crabcyborg** [comment]
@engahmeds3ed I'm not totally confident it's perfect, no.

It might be nice to actually use an interval so we can solve the modal issue as well.

**Comment by Crabcyborg** [comment]
@engahmeds3ed I just updated this to try an interval instead. I shortened it to 400ms now as well so it should be more instant when the visibility change happens.

It should solve the modal issue as well.

Could you help test it out?

Thank you!

**Comment by engahmeds3ed** [comment]
I tested this change for that case and it works perfectly.

Let me validate with the modal issue.

**Comment by engahmeds3ed** [comment]
It works perfectly also with the modal issue, u r awesome @Crabcyborg 

The only risk here is that the interval will keep working forever till the modal trigger button is clicked, once it's clicked and the form appears, we will clear that interval.
I think this is acceptable risk as we only do a small check each time.

**Comment by Crabcyborg** [comment]
Thanks @engahmeds3ed!

Yeah, I think it should be fine. It only happens if it's hidden as well and helps to fix the whole class of new tickets that have been coming up because of this visibility check.

**Pull request merged**
