### PR TITLE
Fix PayPal action redirecting to a blank page

### PR DESCRIPTION
**Pull request by truongwp**
Fixes https://github.com/Strategy11/formidable-paypal/issues/42

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@garretlaxton Can you help test this out? It would be good to test with confirmation actions that use the message option as well as ones that use the redirect. And to test with PayPal, and to test with Stripe.

I'm hoping to release this today in the next couple of hours as it's a pretty important issue.

Thank you!

**Comment by Crabcyborg** [comment]
@truongwp Is it possible to add unit tests to cover the PayPal issue?

**Comment by truongwp** [comment]
@Crabcyborg Can it be added later? I'm not sure I will be able to work in the next couple of hours.
I also see one failing unit test. I think the test inside the `if (headers_sent())` is enough, right?

**Comment by Crabcyborg** [comment]
> I think the test inside the `if (headers_sent())` is enough, right?

@truongwp That may only be enough if headers_sent is always true. Would it work in a `assertTrue( headers_sent() )` first or are there cases where it would be false while running the unit test?

I'm also concerned why it would be broken with this update when that unit test passes in master. Why it this update causing a breaking test?

**Comment by Crabcyborg** [comment]
@truongwp I think it's failing because this line here doesn't filter the success_url https://github.com/Strategy11/formidable-forms/blob/7ec1189ff7a0f56643b51f9560bd3593166a055b/classes/controllers/FrmFormsController.php#L2582

**Comment by garretlaxton** [comment]
I just finished looking at this and PayPal worked fine for me. 

I do have an issue with Stripe when using a redirect though, I'm taken to my wp-admin page instead of the URL set in the confirm action. Should I log that in the Stripe repo?

**Comment by Crabcyborg** [comment]
> I do have an issue with Stripe when using a redirect though, I'm taken to my wp-admin page instead of the URL set in the confirm action. Should I log that in the Stripe repo?

@garretlaxton If that with Stripe link on only, and for a URL that isn't to your own site?

I believe I've seen this happen - because I'm using `wp_safe_redirect` which doesn't let you go to an external site. I should update this but I haven't prioritized it as I haven't seen it come up in support yet.

**Comment by truongwp** [comment]
> I think it's failing because this line here doesn't filter the success_url

@Crabcyborg I think confirmation actions aren't run when you run `show_form()`.

**Pull request merged**
