### PR TITLE
Add a filter to allow Akismet to modify the values that get sent to the Akismet API

### PR DESCRIPTION
**Pull request by cfinke**
This will allow the Akismet plugin to have better integration and supply more relevant data for spam checks.

We're working on improving Akismet's accuracy with contact forms, and this filter will allow us to have the same level of integration that we have with Jetpack, Gravity Forms, and Contact Form 7.

If there's an existing way for another plugin to add additional information to the `$datas` array that gets sent to Akismet, let me know.

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@stephywells what do you think about this? If we're making a release, this might make sense to include in the release as well.

**Review by stephywells — APPROVED** [review]
Awesome! Thanks so much @cfinke ! We appreciate your help.

**Comment by cfinke** [comment]
Thank you!

**Comment by Crabcyborg** [comment]
Having issues getting phpcs to run on this branch because of the fork. I'm closing this, and made the same update in another pull request.

https://github.com/Strategy11/formidable-forms/pull/555

**Pull request closed without merging**
