### PR TITLE
validate message data before rendering it

### PR DESCRIPTION
**Pull request by Crabcyborg**
I'm working toward a solution for https://github.com/Strategy11/formidable-pro/issues/2879

This at least avoids all of the errors that happen when you load the inbox.

### CODE REVIEW

**Review by stephywells — COMMENTED** [review]
It might make sense to add this check right before line 112 too:
$this->messages[ $message['key'] ] = $message;

This would prevent the message from being added, rather than adding it and then removing it later.

**Comment by Crabcyborg** [comment]
> It might make sense to add this check right before line 112 too:
> $this->messages[ $message['key'] ] = $message;
> 
> This would prevent the message from being added, rather than adding it and then removing it later.

@stephywells Sorry for not getting to that already! Added now.

**Comment by stephywells** [comment]
Hmm... That's weird. How did the message get added? Do you have a copy/paste of the saved array by chance?

**Comment by stephywells** [comment]
Nevermind. I see it in the issue. I'm looking over that a bit more.

**Comment by stephywells** [comment]
Okay, it seems like the better fix would be to remove anything with a blank key. The key should always have a value. That might be where the api error came in. So instead of checking for all of the array keys that should be filled in automatically, let's unset anything with a blank key.

Would changing
if ( $this->is_expired( $message ) || $dismissed ) {
to:
if ( empty( $k ) || $this->is_expired( $message ) || $dismissed ) {

do it?

**Comment by stephywells** [comment]
And maybe this too?

	public function mark_read( $key ) {
		if ( ! $key || ! isset( $this->messages[ $key ] ) ) {

**Comment by Crabcyborg** [comment]
@stephywells sounds good, starting from scratch with those. This removes the error, and it's simpler.

Closing this PR, new PR is here - https://github.com/Strategy11/formidable-forms/pull/346

**Pull request closed without merging**
