### PR TITLE
Placeholder icon for google sheets addon

### PR DESCRIPTION
**Pull request by omidakhavans**
Add placeholder icon for google sheets add-on.

Fixes https://github.com/Strategy11/formidable-pro/issues/3882

### CODE REVIEW

**Review by Crabcyborg — APPROVED** [review]
Thanks @omidakhavans! I'm wondering if we should define a color here but I see we aren't in the other plugin yet.

I brought it up in check-in. For now I'm good with just merging this though.

**Comment by omidakhavans** [comment]
@Crabcyborg Thank you very much, Please let me know I can add the colors too.

**Comment by Crabcyborg** [comment]
@omidakhavans Steph agreed we should lock in a color. Our `var(--green)` value is really close to Google's green so it's probably fine to just use that.

**Comment by omidakhavans** [comment]
@Crabcyborg Done. Thank you. Related PR https://github.com/Strategy11/formidable-forms/pull/964

**Pull request merged**
