### PR TITLE
Add condition to avoid js warnings for a null property

### PR DESCRIPTION
**Pull request by jairoprez**
This PR should do the trick to fix the JS error reported by @altoin 
download - 2021-01-05T105636 519

https://sandbox.formidableforms.com/toyin/wp-admin/admin.php?page=formidable&frm_action=edit&id=936

### CODE REVIEW

**Review by Crabcyborg — APPROVED** [review]
@jairo this should do the trick. Usually I'd avoid the repeat logic of getting the element twice like this, but I don't imagine that's too life or death here.

**Comment by jairoprez** [comment]
> @Jairo this should do the trick. Usually I'd avoid the repeat logic of getting the element twice like this, but I don't imagine that's too life or death here.

Thanks @Crabcyborg - Anyway, I have applied your suggestion :zany_face:.

**Comment by Crabcyborg** [comment]
@jairoprez ESLint seems a little unhappy now.

I'm seeing:

```
1059:2   error    Mixed spaces and tabs                                            no-mixed-spaces-and-tabs
1060:5   error    Trailing spaces not allowed                                      no-trailing-spaces
```

There's also the infamous `warning  All 'var' declarations must be at the top of the function scope  vars-on-top` that we break all over. I try not to introduce more of these either.

**Comment by jairoprez** [comment]
> @jairoprez ESLint seems a little unhappy now.
> 
> I'm seeing:
> 
> ```
> 1059:2   error    Mixed spaces and tabs                                            no-mixed-spaces-and-tabs
> 1060:5   error    Trailing spaces not allowed                                      no-trailing-spaces
> ```

@Crabcyborg ESLint seems happy now. Thanks!

**Comment by jairoprez** [comment]
@stephywells The warnings for `All 'var' declarations must be at the top of the function scope vars-on-top` have been fixed.

**Comment by stephywells** [comment]
Thanks @jairoprez! Looks like this will need a bunch more testing before we can merge. In the meantime, can you submit a new pr with just the change you had before? But this time, be sure to keep the var at the top of the function. We don't need to fix all of it right now, just to the parts we make changes to.

**Comment by jairoprez** [comment]
@stephywells Oh sorry, I thought I should fix them all, I have reverted the unnecessary changes in this PR.

**Review by stephywells — APPROVED** [review]
Looks great now! Thanks for picking this up!

**Pull request merged**
