### PR TITLE
Upload image button in Radio field should show only images

### PR DESCRIPTION
**Pull request by truongwp**
This fix https://github.com/Strategy11/formidable-pro/issues/3018

### CODE REVIEW

**Review by Crabcyborg — APPROVED** [review]
@truongwp this looks good!

I don't really see where this could have any issues.

@stephywells can you think of anything that might ever get used as a radio option image that might be actually validate here as an image?

**Comment by stephywells** [comment]
Good call! I can't think of another use case. Even if someone happens to have something selected that isn't an image, this wouldn't cause any issues with existing fields.

Looks good to me! Does this need any QA?

**Comment by truongwp** [comment]
If someone selects a file that isn't an image, it will show a broken image. So I think no one keeps that.

Screen Shot 2021-05-14 at 08 01 00

**Comment by Crabcyborg** [comment]
> Looks good to me! Does this need any QA?

I just looked at it quickly. It appears to filter the options to images only. It looks like uploading a non-image is still possible, so we're really just preventing people from selecting invalid files.

I think this is good as it is. I'm going to merge it. Thanks @truongwp!

**Pull request merged**
