### PR TITLE
add the missing name attribute to independent slider fields

### PR DESCRIPTION
**Pull request by Liviu-p**
Fixes https://github.com/Strategy11/formidable-pro/issues/5401

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@Liviu-p Is this ready for review? It looks like it's been sitting for some time.

**Comment by Liviu-p** [comment]
> @Liviu-p Is this ready for review? It looks like it's been sitting for some time.

oh, yes. Sorry @Crabcyborg, I missed this one

**Review by truongwp — APPROVED** [review]
This looks good. Thanks @Liviu-p!

**Review by Crabcyborg — APPROVED** [review]
Thanks @Liviu-p and @truongwp!

I just tagged Laura for additional QA.

**Review by lauramekaj1 — APPROVED** [review]
@Liviu-p I tested it and verified as fixed. Thank you!

**Comment by Crabcyborg** [comment]
Thanks Laura! 🚀

**Pull request merged**
