### PR TITLE
Stop using font icons for form actions collapsible

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fix https://github.com/Strategy11/formidable-pro/issues/5249
CleanShot 2024-08-08 at 11 04 37

### CODE REVIEW

**Comment by truongwp** [comment]
@AbdiTolesa I think we can remove this CSS https://github.com/Strategy11/formidable-forms/blob/62e5898163b38ec797cd87ea05f2b2df79c1f493/css/frm_admin.css#L6799

**Comment by truongwp** [comment]
We should add `transition` for the icon, the previous `<i>` tag has a transition CSS rule. We can copy it for the svg and probably remove the CSS rule for that `<i>` tag.

**Comment by AbdiTolesa** [comment]
> We should add `transition` for the icon, the previous `<i>` tag has a transition CSS rule. We can copy it for the svg and probably remove the CSS rule for that `<i>` tag.

@truongwp I have removed the old css, thanks! I didn't see any significant transition effect for the old `<i>` tag, are you referring to the the transition below?
image

**Comment by truongwp** [comment]
@AbdiTolesa Sorry, the old <i> tag doesn't have the transition for rotation.

**Review by truongwp — APPROVED** [review]
This looks good. Thanks @AbdiTolesa!

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa and @truongwp for working on this!

I think this is good to merge.

🚀

**Pull request merged**
