### PR TITLE
Fix issues with toggling pages

### PR DESCRIPTION
**Pull request by Crabcyborg**
Fixes https://github.com/Strategy11/formidable-pro/issues/3121

Page toggle logic had to change a bit since it uses nextUntil but I have the pages wrapped like everything else for consistency.

### CODE REVIEW

**Review by stephywells — COMMENTED** [review]
This works and looks great. I am seeing one js error when I try to collapse a page with no fields.
formidable_admin.js?ver=5.0:4066
Uncaught TypeError: Cannot read property 'querySelector' of null

**Comment by Crabcyborg** [comment]
> Uncaught TypeError: Cannot read property 'querySelector' of null

Thanks @stephywells nice catch! I've pushed a check for the initial value of the first wrapper as well.

**Review by stephywells — APPROVED** [review]
Perfect!

**Review by garretlaxton — APPROVED** [review]
Collapsing the first page no longer collapses all the pages.

Screenshot 2021-08-12 at 14-33-57 Formidable Forms ‹ Formi QA — WordPress

I tested this with 8 pages like the ticket and all pages collapse individually.

**Comment by Crabcyborg** [comment]
Thank you for testing @garretlaxton and @stephywells!

**Pull request merged**
