### PR TITLE
Avoid changing the label position container classes if a field does not use the default

### PR DESCRIPTION
**Pull request by Crabcyborg**
Fixes https://github.com/Strategy11/formidable-pro/issues/4072

The old code for this was fine because it was for the sample form where this setting doesn't exist. I hadn't considered this field setting.

This update adds a class to any field with the default set, and only those get changed now.

### CODE REVIEW

**Review by garretlaxton — APPROVED** [review]
This looks good!
image

Should this apply to the form builder though?
image

**Comment by Crabcyborg** [comment]
@garretlaxton That's an interesting question. I think that might just make the field more difficult to update without a label.

That page isn't as true of a preview so it's probably fine leaving it as is for now.

**Review by stephywells — COMMENTED** [review]
@Crabcyborg Nice! I didn't test this to make sure... Does this cover the preview form when not editing the style too?

**Review by stephywells — APPROVED** [review]

**Comment by Crabcyborg** [comment]
> Does this cover the preview form when not editing the style too?

Yes, it does. The HTML for the styler preview is identical for both the edit/list views, and the `setPosClass` function here is used for both as well. It just fakes the position input on the list page based on the label position setting of the selected style card.

**Pull request merged**
