### PR TITLE
improve primary color from quick settings style editor

### PR DESCRIPTION
**Pull request by Liviu-p**
Fixes https://github.com/Strategy11/formidable-pro/issues/5377

### CODE REVIEW

**Review by shervElmi — APPROVED** [review]
Thanks @Liviu-p, it looks great to me. 🚀

However, when the Pro add-on isn't activated, the color pickers' colors are missing as shown below:

CleanShot 2024-10-16 at 18 42 35@2x

There is a strong white color that, if disabled, will fix it:

CleanShot 2024-10-16 at 18 44 58@2x

CleanShot 2024-10-16 at 18 44 13@2x

Are you aware of this, or is it a new issue?

**Comment by Liviu-p** [comment]
> Thanks @Liviu-p, it looks great to me. 🚀
> 
> However, when the Pro add-on isn't activated, the color pickers' colors are missing as shown below:
> 
> CleanShot 2024-10-16 at 18 42 35@2x
> 
> There is a strong white color that, if disabled, will fix it:
> 
> CleanShot 2024-10-16 at 18 44 58@2x
> 
> CleanShot 2024-10-16 at 18 44 13@2x
> 
> Are you aware of this, or is it a new issue?

Nice catch @shervElmi, I wasn't aware of it. Thank you for pointing it out!. Could please take another look over it?

**Review by shervElmi — APPROVED** [review]
Thanks for the update @Liviu-p, it looks great to me! 🚀

**Review by Crabcyborg — APPROVED** [review]
Thanks @Liviu-p and @shervElmi for working on this!

I think this looks good to merge.

🚀

**Pull request merged**
