### PR TITLE
Fix confirmation action is forced to message

### PR DESCRIPTION
**Pull request by truongwp**
Fixes https://github.com/Strategy11/formidable-pro/issues/4101

My last fix added `$method = 'message'` to show the default message if no actions match. But it breaks the form that hasn't been migrated. I added a check if the form hasn't been migrated there.

### CODE REVIEW

**Comment by truongwp** [comment]
I'm checking why phpunit tests failed.

**Review by stephywells — APPROVED** [review]
Looks good to me! I move the code to get the fallback so we don't have to add it in other places too.

Actually... Looks like the unit tests are failing. Looking into it.

**Comment by truongwp** [comment]
@stephywells We have a different fallback edit message. Can you update it? I’m away from desk now.

**Comment by stephywells** [comment]
Thanks for checking this! I think we need a hook or something to cover that. For now, I think it's fine if the fallback uses the same message.

**Pull request merged**
