### PR TITLE
skip js validation for readonly/disabled fields

### PR DESCRIPTION
**Pull request by Liviu-p**
Fixes https://github.com/Strategy11/formidable-pro/issues/4447

### CODE REVIEW

**Comment by garretlaxton** [comment]
Should I still get a error when the time field is blank even though it's read-only?
image

**Comment by Liviu-p** [comment]
> Should I still get a error when the time field is blank even though it's read-only? image

I'm not sure about this, it makes sense to me to trigger the error as long it is set up as required + readonly. @Crabcyborg   what do you think?

**Comment by Crabcyborg** [comment]
Thanks @Liviu-p and @garretlaxton. This seems like a weird conflict of settings the more I think about this.

I don't understand how something would make sense as read only, and also required, with no default value. It seems like something that should display a warning in the form builder.

@stephywells What do you think makes sense here? Should we really validate anything disabled with JS? When it's disabled, no value gets sent anyway so I don't know why we'd validate it before its sent.

**Comment by stephywells** [comment]
@Crabcyborg it seems like a validation message isn't helpful if the user can't do anything about it. But we also don't want to allow people to manually clear out the read only value and then get past validation. 

This does seem to me like more of an error on the builder end that we should notify of the issue. Is it possible to handle this type of error with a message on the builder page like you mentioned?

**Comment by Crabcyborg** [comment]
Thanks @stephywells! We'll look into adding a warning.

**Comment by Crabcyborg** [comment]
@Liviu-p Could you try to work on that when you have the chance?

**Comment by Liviu-p** [comment]
> @Liviu-p Could you try to work on that when you have the chance?

sure @Crabcyborg, I will take care of it.

**Comment by Crabcyborg** [comment]
I'm going to close this PR for now.

I think we can leave the validation as-is for now.

I fixed this issue in another way (See https://github.com/Strategy11/formidable-forms/pull/1946), by addressing the JS error instead.

**Pull request closed without merging**
