### PR TITLE
fix radio button field style issues

### PR DESCRIPTION
**Pull request by AbdiTolesa**
This update just fixes some style issues found in radio fields.

### CODE REVIEW

**Comment by garretlaxton** [comment]
I'm not seeing any fixes for the scale field in this PR.
image

The radio buttons are fine now though.
image

**Comment by AbdiTolesa** [comment]
> I'm not seeing any fixes for the scale field in this PR. image
> 
> The radio buttons are fine now though. image

This is just for the radio fields @garretlaxton

**Review by garretlaxton — APPROVED** [review]
Thanks, I meant to come back to this after seeing the other PR.

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa the radios looks a lot better now!

**Pull request merged**
