### PR TITLE
bootstrap update v5

### PR DESCRIPTION
**Pull request by Liviu-p**

### CODE REVIEW

**Comment by Crabcyborg** [comment]
@Liviu-p Unfortunately we're a bit stuck on Bootstrap 4.

Our multiselect inputs used for a few settings, including Field Visibility and Global Permissions, use https://github.com/davidstutz/bootstrap-multiselect

It still doesn't support Bootstrap 5. See this open issue https://github.com/davidstutz/bootstrap-multiselect/issues/1189

Screen Shot 2024-01-17 at 10 43 48 AM
Screen Shot 2024-01-17 at 10 44 26 AM

**Comment by Liviu-p** [comment]
> @Liviu-p Unfortunately we're a bit stuck on Bootstrap 4.
> 
> Our multiselect inputs used for a few settings, including Field Visibility and Global Permissions, use https://github.com/davidstutz/bootstrap-multiselect
> 
> It still doesn't support Bootstrap 5. See this open issue [davidstutz/bootstrap-multiselect#1189](https://github.com/davidstutz/bootstrap-multiselect/issues/1189)
> 
> There's a solution there that looks promising. Maybe we can try [davidstutz/bootstrap-multiselect#1189 (comment)](https://github.com/davidstutz/bootstrap-multiselect/issues/1189#issuecomment-977523734)
> 
> Screen Shot 2024-01-17 at 10 43 48 AM Screen Shot 2024-01-17 at 10 44 26 AM

thank you so much @Crabcyborg, for pointing it out and sharing these details! I'll give it try to see how I can make it work with Bootstrap 5

**Comment by Liviu-p** [comment]
Hey @Crabcyborg, I'll close it for now. Looks like Bootstrap 5 updates requires more work on fixing breaking changes. I've managed to fix the issue and keeping Bootstrap 4.6

**Comment by Crabcyborg** [comment]
Thank you @Liviu-p!

**Pull request closed without merging**
