### PR TITLE
call do_shortcode on field name when inserting a shortcode with customization sidebar

### PR DESCRIPTION
**Pull request by Crabcyborg**
Fixes https://github.com/Strategy11/formidable-pro/issues/1459 for the customization sidebar.
Together with https://github.com/Strategy11/formidable-pro/pull/2933 which handles the entries list, this closes the ticket.

### CODE REVIEW

**Review by jairoprez — APPROVED** [review]
This is working great https://recordit.co/eTw156dX1S 🎉

**Comment by stephywells** [comment]
@jairoprez It doesn't look like your video covered this part...
screen shot 2017-01-14 at 3 14 42 pm

Did you already take a look at that too?

**Comment by Crabcyborg** [comment]
I am closing this for now as I think this needs a more universal solution.

**Comment by jairoprez** [comment]
> @jairoprez It doesn't look like your video covered this part...
> screen shot 2017-01-14 at 3 14 42 pm
> 
> Did you already take a look at that too?

@stephywells sorry for the delay in answering, I had not noticed this question, you're right, I don't think I took a look at that part.

> @jairoprez It doesn't look like your video covered this part...
> screen shot 2017-01-14 at 3 14 42 pm
> 
> Did you already take a look at that too?

@stephywells  Sorry for the delay in responding, I had not noticed this comment before, you're right I didn't take a look at this part but I already took a look and the fix also seems to work fine for the customization area of views https://recordit.co/GFgB4jfKVN

Thanks for pointing that out to me.

**Pull request closed without merging**
