### PR TITLE
Remove width limit from h1 title

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fix https://github.com/Strategy11/formidable-pro/issues/5173
### Test steps
Switch your site language to Portuguese/Brazillian and go to the form entries page.

**Before**:
CleanShot 2024-07-08 at 11 08 50@2x

**After**:
CleanShot 2024-07-08 at 11 08 12@2x

### CODE REVIEW

**Comment by AbdiTolesa** [comment]
@Crabcyborg I couldn't switch to Portuguese (Brazilian) locally but I can see the issue in QA and just created this PR quickly. The parent `div` has `frm_top_left` which constraints the width and I assume it is safe to just get rid off the width limitation on the `h1`.

**Comment by AbdiTolesa** [comment]
> @AbdiTolesa I think we may want to force a minimum width at least. Changing it to `min-width` is probably better than removing the width style.

Thanks, done!

**Review by truongwp — APPROVED** [review]
This looks good. Thanks @AbdiTolesa!

**Review by Crabcyborg — APPROVED** [review]
I'm not seeing any issues with this change.

Thanks @AbdiTolesa and @truongwp!

🚀

**Pull request merged**
