### PR TITLE
Enhance UI/UX of Application cards

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fix https://github.com/Strategy11/formidable-pro/issues/5328

**Design** by Razvan: https://github.com/Strategy11/formidable-pro/issues/5328#issuecomment-2332233644

CleanShot 2024-11-01 at 11 10 05

### Test procedure
1. Go to Formidable -> Applications and confirm that the 'NEW' badge and Add/Learn more buttons are inline with the Application title and hovering on the cards would switch between the badge and buttons.
2. Confirm that Applications with a really long name are truncated with `...` but the buttons are always appear inline with it.

### CODE REVIEW

**Review by lauramekaj1 — APPROVED** [review]
@AbdiTolesa I tested this and verified it's working as expected. Thank you!

**Review by truongwp — APPROVED** [review]
This looks good. Thanks @AbdiTolesa!

**Review by Crabcyborg — APPROVED** [review]
Thanks @AbdiTolesa @truongwp and @lauramekaj1 for working on this!

I think this looks good to merge.

🚀

**Review by Crabcyborg — CHANGES_REQUESTED** [review]
@AbdiTolesa I noticed a bug with this update.

The customer applications no longer have a delete icon.
Screen Shot 2024-11-04 at 11 51 26 AM

This results in JS errors from Pro as well.
image

**Review by Crabcyborg — APPROVED** [review]
Thanks for updating that @AbdiTolesa!

Some Cypress tests are failing but it looks like it's happening in master as well. It looks related to changes on formidableforms.com and not related to this PR.

I'll go ahead and merge this.

🚀

**Pull request merged**
