### PR TITLE
Export/import view layouts

### PR DESCRIPTION
**Pull request by Crabcyborg**

### CODE REVIEW

**Review by stephywells — COMMENTED** [review]
@Crabcyborg Do you think it would be worth adding a hook here instead?

**Comment by Crabcyborg** [comment]
> @Crabcyborg Do you think it would be worth adding a hook here instead?

@stephywells I'm not sure, I had to update it in 7 spots to get import working now so that might be pretty tricky to add hooks for all of those positions.

**Comment by stephywells** [comment]
Oh, weird. I only saw the posts_xml.php file before. I must have just been looking at one commit.

**Comment by Crabcyborg** [comment]
> Oh, weird. I only saw the posts_xml.php file before. I must have just been looking at one commit.

@stephywells yeah, sorry, I had requested your review when it was just supporting the export. I hadn't worked out all of the import stuff yet. I didn't know until recently how off the export actually was (the first commit ended up being incomplete).

**Review by stephywells — APPROVED** [review]
This looks good. Do we need Garret and Jairo to run through the QA on this?

**Comment by Crabcyborg** [comment]
> This looks good. Do we need Garret and Jairo to run through the QA on this?

Wouldn't hurt!

**Review by garretlaxton — APPROVED** [review]
These new views are really incredible! 

I was able to successfully export & import a new view for a contact form on my localhost to my live blog.

**Review by jairoprez — APPROVED** [review]
@stephywells @Crabcyborg I did tests with different use cases and they all ran successfully 🎉 

- https://recordit.co/u1ehq90B5u (did tests with the 7 existing grids one by one in separate layouts)
- https://recordit.co/92iAe5ogx4 (did tests using the repeater field)
- https://recordit.co/zKYng2cWHI (did tests with the 7 existing grids all together in the same layout)

Awesome Job! @Crabcyborg 💪

**Comment by Crabcyborg** [comment]
Thank you @jairoprez and @garretlaxton!

**Pull request merged**
