### PR TITLE
Checkbox and Radio Button Style Issues After New Style Update

### PR DESCRIPTION
**Pull request by shervElmi**
This PR resolves style issues with radio buttons and checkboxes that appeared after the recent style update.

### Pro PR:
https://github.com/Strategy11/formidable-pro/pull/5323

#### Tickets
[208510](https://secure.helpscout.net/conversation/2691959080/208510?folderId=2445391), [208405](https://secure.helpscout.net/conversation/2690942720/208405?folderId=2445394), [208389](https://secure.helpscout.net/conversation/2690874071/208389/)

#### Video
https://www.loom.com/share/ff2125f4e30b426e8159ffc9f2190b6c

### CODE REVIEW

**Comment by garretlaxton** [comment]
This looks good, but when it is set to show images they show vertically in the style editor. 
image
image

**Comment by shervElmi** [comment]
@Crabcyborg and @garretlaxton,

Thanks for your review.

Garret, the issue is from the FF Surveys Add-on, and I’ll fix it here:  
https://github.com/Strategy11/formidable-surveys/pull/298

**Review by garretlaxton — APPROVED** [review]
Thanks! Everything looks good here now!

**Comment by Crabcyborg** [comment]
Thank you Garret!

🚀

**Pull request merged**
