### PR TITLE
Fix Footer Misplacement on Initial Page View

### PR DESCRIPTION
**Pull request by shervElmi**
This PR addresses the issue of the footer being misplaced at the bottom when first viewing a page. The footer will now appear in its correct position without requiring the user to scroll.

## Related Issue:
[Footer Misplacement on Initial Page View](https://github.com/Strategy11/formidable-pro/issues/4508)

## QA URL
https://qa.formidableforms.com/sherv2/wp-admin/admin.php?page=formidable-entries&frm_action=new

## Testing Instruction:
1. Navigate to `WP Admin > admin.php?page=formidable-entries&frm_action=new`.
2. Verify the footer is now in its correct position on initial page view, without needing to scroll down.

### After
image

### CODE REVIEW

**Comment by truongwp** [comment]
@shervElmi Can you fix the issue without extra JS? I found that when scrolling, this CSS is added to the `<div id="adminmenuwrap"` element: `position: fixed; bottom: 0px;`. I think we can add that CSS.

Please make sure it doesn't affect other pages that don't contain this footer.

When the admin menu is collapsed, please adjust the padding left of this footer. We have that CSS, but for small screen.

**Comment by shervElmi** [comment]
Thank you for your review @truongwp, but since we utilize this feature on all pages under varying conditions, using JS is the better approach. Your solution might cause a bug when we have a WP footer, as it also employs this CSS and may create an overlapping issue. It's risky here to use CSS as previously done.

**Comment by truongwp** [comment]
@shervElmi That's ok.

Can you fix the left padding when the menu bar is collapsed?

**Comment by shervElmi** [comment]
@truongwp, I've not been able to see the problem you mentioned. Could you please send me a gif or an image to help clarify and show the issue? Thanks!

**Comment by truongwp** [comment]
@shervElmi This is the video I recorded:

https://github.com/Strategy11/formidable-forms/assets/19748318/1c9b14de-3e1f-4e6d-a670-9418d8cc69bb

**Comment by shervElmi** [comment]
@truongwp, I think this video shows the earlier version of the Footer Links. You might need to clear your cache or insert `define( 'SCRIPT_DEBUG', true );` into your `wp-config.php` file.

**Review by truongwp — APPROVED** [review]
Thanks @shervElmi. This works for me now. I have to clear my browser cache.

**Review by Crabcyborg — CHANGES_REQUESTED** [review]
@shervElmi There aren't enough checks here.

If you use whitelabeling and there are no footer links, there's a JS error.

Screen Shot 2023-11-03 at 4 27 12 PM

**Review by Crabcyborg — APPROVED** [review]
Thanks for updating that @shervElmi.

And thank you @truongwp and @garretlaxton for reviewing this!

🚀

**Pull request merged**
